### ISSUE TITLE
Прикрутить самсаб

### ISSUE THREAD

**Issue by dapi** [bitzlato/barong#71]
## Этап I

самсаб независимо работает на barong

* [x] endpoint который возвращает ссылку на прохождение верифицакии
* [x] endpont который принимает вебхук от самса
* [x] изменение статуса верификации у пользователя (4 статуса)
* [x] менеджерский endpoint который сбрасывает статус у пользователя (у нас и в самсаб)
* [x] сохранять историю изменений статуса (они могут меняться и сбрасываться). можно прикрутить что-то типа PaperTrail

- [ ] https://github.com/ankane/the-ultimate-guide-to-ruby-timeouts
- [x] JWT
- [x] добавит v1

## Этап II

Интеграция с p2p

* [ ] Устанавливаются нужные флажки в p2p (напрямую в базе или через API)
* [ ] Отправляется нужное уведомление в боты, веб и мобилку

**Comment by elnikov** [comment]
## Виды вебхуков 
![image](https://user-images.githubusercontent.com/2846153/150369152-8f1d4ab2-f999-4d6a-8989-fd12ff6ce394.png)

## Статусы заявки

![image](https://user-images.githubusercontent.com/2846153/150370421-9f5c3787-a505-4b87-9100-d704f2a11a3e.png)
![image](https://user-images.githubusercontent.com/2846153/150370511-4711474a-49fd-4aff-8a0a-cd75b8c7a671.png)

## Статусы отказов целая куча 

![image](https://user-images.githubusercontent.com/2846153/150371141-adb5d10a-23d4-4e2e-94d0-870db4a050b4.png)

**Comment by elnikov** [comment]
Не относится к Barong
